// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF4OUscqefFWbkxN-iKttw8cFW_1N2FZQ',
    appId: '1:30466765887:web:14438e459a2cd8210d348a',
    messagingSenderId: '30466765887',
    projectId: 'lockbook-7bcfc',
    authDomain: 'lockbook-7bcfc.firebaseapp.com',
    storageBucket: 'lockbook-7bcfc.firebasestorage.app',
    measurementId: 'G-QXQ6236033',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFDqp0h6B8G4BVSW99vgkonFcXhRcUs4',
    appId: '1:30466765887:android:b040cb58560b22530d348a',
    messagingSenderId: '30466765887',
    projectId: 'lockbook-7bcfc',
    storageBucket: 'lockbook-7bcfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgsN3RaJqhYUWIAAXpDm1XVvWC-sG1Yqk',
    appId: '1:30466765887:ios:32092ce8a3570a2d0d348a',
    messagingSenderId: '30466765887',
    projectId: 'lockbook-7bcfc',
    storageBucket: 'lockbook-7bcfc.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgsN3RaJqhYUWIAAXpDm1XVvWC-sG1Yqk',
    appId: '1:30466765887:ios:32092ce8a3570a2d0d348a',
    messagingSenderId: '30466765887',
    projectId: 'lockbook-7bcfc',
    storageBucket: 'lockbook-7bcfc.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF4OUscqefFWbkxN-iKttw8cFW_1N2FZQ',
    appId: '1:30466765887:web:b8fbe9aab115a39a0d348a',
    messagingSenderId: '30466765887',
    projectId: 'lockbook-7bcfc',
    authDomain: 'lockbook-7bcfc.firebaseapp.com',
    storageBucket: 'lockbook-7bcfc.firebasestorage.app',
    measurementId: 'G-K6QERFS4V3',
  );
}
