// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5MFYBQdeskrkvlswXZHgumH9LpcZ6gyo',
    appId: '1:488031049875:android:e91dd691a40955bf041566',
    messagingSenderId: '488031049875',
    projectId: 'smart-health-reminder-d338f',
    storageBucket: 'smart-health-reminder-d338f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLupJwErBwm05KhLgsBFIwQpPmfQ7JZE4',
    appId: '1:488031049875:web:31c2fb0ff8df598c041566',
    messagingSenderId: '488031049875',
    projectId: 'smart-health-reminder-d338f',
    storageBucket: 'smart-health-reminder-d338f.firebasestorage.app',
    authDomain: 'smart-health-reminder-d338f.firebaseapp.com',
    measurementId: 'G-1R5YHM54FD',
  );
}
