spring.application.name=apsit-canteen-management
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/apsit_canteen_management}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api/v1
server.port=${PORT:8080}

jwt.secretKey=${JWT_SECRET_KEY:sdhfjlsfsfhfshgjljsdlkjshfjllsdfkjglaljlsedisfjksdnvknskdldjihflxhdhlvfs}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Deny any individual file larger than 2MB
spring.servlet.multipart.max-file-size=2MB
# Deny any total request larger than 2MB
spring.servlet.multipart.max-request-size=2MB