// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrBC8UHf9r_nM2zny5VgTyokO2iSL_88',
    appId: '1:1060220221197:web:6277041a7a133eb6102244',
    messagingSenderId: '1060220221197',
    projectId: 'reusexcom',
    authDomain: 'reusexcom.firebaseapp.com',
    storageBucket: 'reusexcom.firebasestorage.app',
    measurementId: 'G-NEJP4ZH1KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoGHib-wTLlhZPIvaeu03Ms5iloUDid5M',
    appId: '1:1060220221197:android:f493f0d0439157fd102244',
    messagingSenderId: '1060220221197',
    projectId: 'reusexcom',
    storageBucket: 'reusexcom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxfwlEgkOXYyeUZI4sKoDyNOvo_F4rjmA',
    appId: '1:1060220221197:ios:9d1046c99b41b75d102244',
    messagingSenderId: '1060220221197',
    projectId: 'reusexcom',
    storageBucket: 'reusexcom.firebasestorage.app',
    iosBundleId: 'com.example.reusexCopy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxfwlEgkOXYyeUZI4sKoDyNOvo_F4rjmA',
    appId: '1:1060220221197:ios:9d1046c99b41b75d102244',
    messagingSenderId: '1060220221197',
    projectId: 'reusexcom',
    storageBucket: 'reusexcom.firebasestorage.app',
    iosBundleId: 'com.example.reusexCopy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZrBC8UHf9r_nM2zny5VgTyokO2iSL_88',
    appId: '1:1060220221197:web:001ebb860a224b6b102244',
    messagingSenderId: '1060220221197',
    projectId: 'reusexcom',
    authDomain: 'reusexcom.firebaseapp.com',
    storageBucket: 'reusexcom.firebasestorage.app',
    measurementId: 'G-5TRQ2PYEJG',
  );
}
