name: canteen_user_app
description: User-facing Flutter app for APSIT Canteen Management System
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  event_bus: ^2.0.1
  flutter_local_notifications: ^17.2.3
  http: ^1.2.2
  shared_preferences: ^2.3.2
  stomp_dart_client: ^2.0.0
  cached_network_image: ^3.4.1
  qr_flutter: ^4.1.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
