// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB61xi98YbjievVQLLztVbIrerpp9L4-oA',
    appId: '1:19730600238:web:d5a527182c9d60dc552abf',
    messagingSenderId: '19730600238',
    projectId: 'smart-student-system',
    authDomain: 'smart-student-system.firebaseapp.com',
    storageBucket: 'smart-student-system.firebasestorage.app',
    measurementId: 'G-SREYWWXHED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRQDn_eK8iPWYoE450-9FBglZQlA3B0k',
    appId: '1:19730600238:android:78f52a52cc4cd13a552abf',
    messagingSenderId: '19730600238',
    projectId: 'smart-student-system',
    storageBucket: 'smart-student-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxi776TfH2q2l8msuDJ1y9Ki0oAKmRIHc',
    appId: '1:19730600238:ios:9a6a80bbcda511de552abf',
    messagingSenderId: '19730600238',
    projectId: 'smart-student-system',
    storageBucket: 'smart-student-system.firebasestorage.app',
    iosBundleId: 'com.example.studentPresenceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxi776TfH2q2l8msuDJ1y9Ki0oAKmRIHc',
    appId: '1:19730600238:ios:9a6a80bbcda511de552abf',
    messagingSenderId: '19730600238',
    projectId: 'smart-student-system',
    storageBucket: 'smart-student-system.firebasestorage.app',
    iosBundleId: 'com.example.studentPresenceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB61xi98YbjievVQLLztVbIrerpp9L4-oA',
    appId: '1:19730600238:web:a8b9b9a9fd086b00552abf',
    messagingSenderId: '19730600238',
    projectId: 'smart-student-system',
    authDomain: 'smart-student-system.firebaseapp.com',
    storageBucket: 'smart-student-system.firebasestorage.app',
    measurementId: 'G-RSTNM10FMC',
  );

}