name: uniaccess
description: UniAccess — Network Access Control System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_parser: ^4.0.2
  web_socket_channel: ^3.0.0
  url_launcher: ^6.2.5
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"